channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.3
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.1
  - lz4==4.4.4
  - numpy==2.2.6
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
